---
# tasks file for roles/database
- name: Tirer et lancer le container Docker '{{ app_name }}'
  docker_container:
    name: "{{ app_name }}"
    image: "{{ docker_image }}"
    state: started
    recreate: true
    pull: true
    network_mode: "{{ network }}"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_db }}"

- name: Afficher le message de confirmation
  debug:
    msg: "{{ app_name }} is running ..."
