---
# tasks file for roles/app
- name: Tirer et lancer le container Docker '{{ app_name }}'
  docker_container:
    name: "{{ app_name }}"
    image: "{{ docker_image }}"
    state: started
    recreate: true
    pull: true
    network_mode: "{{ network }}"
    env:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_USER: "usr"
      POSTGRES_DB: "db"
    published_ports:
      - "{{ port_expose }}"

- name: Afficher le message de confirmation
  debug:
    msg: "{{ app_name }} is running ..."
