---
# tasks file for roles/app

- name: Arrêter et supprimer le container Docker '{{ app_name }}' s'il existe
  docker_container:
    name: "{{ app_name }}"
    state: absent
  ignore_errors: true

- name: Tirer et lancer le container Docker '{{ app_name }}'
  docker_container:
    name: "{{ app_name }}"
    image: "{{ docker_image }}"
    state: started
    recreate: true
    pull: true
    network_mode: "{{ network }}"
    published_ports:
      - "{{ port_expose }}"
    env:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_USER: "usr"
      POSTGRES_DB: "db"

- name: Afficher le message de confirmation
  debug:
    msg: "{{ app_name }} is running ..."
