---
- name: Configurer et lancer des services via Docker
  hosts: all
  become: true
  tasks:
    - name: Tâches globales avant les rôles
      debug:
        msg: "Exécution de tâches globales"
  roles:
    - docker
    - network
    - database
    - app
    - app-2
    - frontend
    - proxy
