- name: Configurer et lancer des services via Docker
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/shared_vars.yml
  roles:
    - docker
    - network
    - database
    - app
    - proxy
  tasks:
    - name: Tester la connexion
      ping: