---
# tasks file for roles/proxy

- name: Arrêter et supprimer le container Docker '{{ app_name }}' s'il existe
  docker_container:
    name: "httpd"
    state: absent
  ignore_errors: true

- name: Tirer et lancer le container Docker '{{ app_name }}'
  docker_container:
    name: "httpd"
    image: "{{ docker_image }}"
    state: started
    recreate: true
    pull: true
    network_mode: "{{ network }}"
    published_ports:
      - "{{ port_expose }}"

- name: Afficher le message de confirmation
  debug:
    msg: "{{ app_name }} is running ..."
