name: CI devops build and push Docker image
on:
  workflow_run:
    workflows: ["CI devops test backend"]
    branches: [main]
    types:
      - completed
jobs:
  build-and-push-docker-image:
    name: "Build and push Docker image"
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-backend:1.0.0
          push: true
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./db
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-database:1.0.0
          push: true
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./webserver
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-httpd:1.0.0
          push: true
