name: CI devops 2023
on:
  push:
    branches: main
jobs:
  test-backend:
    name: "Test de l'application Spring"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build and test with Maven
        working-directory: ./backend/simpleapi
        run: mvn clean verify

      - name: Quality gate with Sonar
        working-directory: ./backend/simpleapi
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tp-cpe-devops_tp-devops -Dsonar.organization=tp-cpe-devops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

  build-and-push-docker-image:
    name: "Build and push Docker image"
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-backend:1.0.0
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./db
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-backend:1.0.0
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./webserver
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops-backend:1.0.0
          push: ${{ github.ref == 'refs/heads/main' }}
